### ISSUE TITLE
Unable to read license file

### ISSUE THREAD

**Issue by steven-huey** [bitstadium/HockeySDK-Mac#69] opened 2016-05-11 18:03 UTC
When installing the HockeySDK-Mac SDK using cocoapods-1.0.0 I'm seeing an error about being unable to read the license file.

```
[!] Unable to read the license file
`/<path>/Pods/HockeySDK-Mac/HockeySDK-Mac/LICENSE.txt` for the spec `HockeySDK-Mac (4.0.0)`
```

**Comment by lumaxis** [comment] 2016-05-11 22:58
Thanks @steven-huey. The cause for this was an error where the License file was wrongly referenced as `.txt` whereas it actually is a Markdown file. This was fixed in https://github.com/bitstadium/HockeySDK-Mac/commit/206ce14a086f98647a01176ee0c908559cb91800 and will be part of the next release.

**Closed by lumaxis** 2016-05-11 22:58 UTC

**Comment by steven-huey** [comment] 2016-05-13 14:19
Thanks!
