### ISSUE TITLE
Permission denied with HockeySDK-Mac 3.1.0

### ISSUE THREAD

**Issue by hankinsoft** [bitstadium/HockeySDK-Mac#48] opened 2015-07-24 14:25 UTC
Codesigning fails when using HockeySDK 3.1.0 as a podfile:

/Users/me/Library/Developer/Xcode/DerivedData/myapp-dbdbwsldpewhrxckkljbgggzsfov/Build/Products/Debug/myapp.app: Permission denied
In subcomponent: /Users/me/Library/Developer/Xcode/DerivedData/myapp-dbdbwsldpewhrxckkljbgggzsfov/Build/Products/Debug/myapp.app/Contents/Frameworks/HockeySDK.framework

**Comment by iosdev-republicofapps** [comment] 2015-09-12 06:18
I am also getting this error.  I cannot codesign.  I have made no other changes to my project, keychain, prov prof or anything related.  The same project that codesigns just fine with HockeySDK-Mac 3.0.0 now fails with 3.1.0.

This seems like a critical bug.  Can you update the instructions and let us know how to fix this?

Is this perhaps because the bug fix "fix code signing issues" in 3.1.0 didn't fix issues (there were none in 3.0.0 for me) but actually created other code signing issues?

Thanks!

**Comment by anlinde** [comment] 2015-09-14 09:20
The change in 3.1 labeled "Solved code signing issues" is related to embedding PLCrashReporter as a static library into the HockeySDK framework and not using it as an inner framework inside HockeySDK. Now there is only one framework with no other framework inside of it, which makes code signing easier and fixes some issues people had because Xcode wouldn't correctly sign both frameworks.

I just tried to reproduce this and integrated the 3.1.0 SDK into a sample project with CocoaPods and added code signing to the release build configuration with a "Developer ID" certificate. Everything works just fine.

Could you please provide a sample project that shows this issue so we can inspect it?

**Comment by ghoover** [comment] 2015-09-15 02:01
I'm seeing the same thing here.  Just upgraded and code signing is failing.

**Comment by iosdev-republicofapps** [comment] 2015-09-15 02:15
@ghoover thanks for the tip!  Let me try that and get back to you.

I wonder why the file perms would matter though?

@anlinde any idea?

I don't have a demo project to attach but I could try to make one.

**Comment by ghoover** [comment] 2015-09-15 03:32
The perms matter because codesign modifies the bundle (from what I understand).  So if it's not writable it can't do that.

**Comment by anlinde** [comment] 2015-09-15 09:16
The perms of the SDK in our distribution zip files are fully identical for version 3.0 and 3.1 and didn't change. Tried reproducing the issue again but with no success.

What are the access rights of the framework before changing them? For me they are set to `drwxrwxrwx` without me doing anything.

**Comment by iosdev-republicofapps** [comment] 2015-11-08 23:35
This issue is happening again with 3.2.0.  It was **not** fixed in 3.1.0 as far as I can tell.  I am on a Mac running Yosemite 10.10.5 and Xcode Version 7.1 (7B91b).  I had tried to update to 3.2.0, then saw this issue, then downgraded to 3.1.0 and it still persists.  So something in your code or your Cocoapod is messing up these file perms.

Any ideas how to fix this?  :-)

Thanks!

**Comment by iosdev-republicofapps** [comment] 2015-11-08 23:40
Here's proof:

```
# Before pod update to HockeySDK-Mac 3.2.0
ls -l ./Pods/HockeySDK-Mac/HockeySDK-Mac
total 8
drwxrwxrwx  7 joel  staff   238B Nov  8 15:38 HockeySDK.framework/

# After pod update to HockeySDK-Mac 3.2.0
ls -l ./Pods/HockeySDK-Mac/HockeySDK-Mac
total 8
drwxr-xr-x  7 joel  staff   238B Nov  8 15:38 HockeySDK.framework/
```

So something is clearly wrong with either the Cocoapod or the HockeySDK-Mac because the file perms are getting modified and this is breaking code signing.

**Comment by anlinde** [comment] 2015-11-09 13:02
The default file permission attributes for all files on OS X and also the content of the distribution zip file is `755`, which means your user, your group and world has read access, write access is restricted to your user. 

Providing write access for group and world doesn't sound like this can be a solution to the real issue, just feels rather like something the coincidentally fixes the issue too. The problem must be somewhere else.

CocoaPods also explicitly changes file permission attributes to `755`, see https://github.com/CocoaPods/CocoaPods/search?utf8=✓&q=chmod

Does your build runs with your user as part of Jenkins/Xcode bot with another user? Do you have any other 3rd party binary frameworks in your app?

**Comment by anlinde** [comment] 2015-12-21 12:38
Closing this ticket as we did get any further details. Please re-open if you have news that could help to solve this.

**Comment by iosdev-republicofapps** [comment] 2015-12-21 14:43
Hi, I appreciate your support, but please re-open as this issue is not fixed!

I am doing a regular old build in Xcode.  No Jenkins, Xcode bot or anything else is involved.  This issue is 100% reproducible, every time.  I have no other 3rd party binary frameworks in my app besides Facebook/Bolts (that are copied in) and also the following CocoaPods in my Podfile:

```
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

pod 'MMMarkdown',     '~> 0.5'
pod 'Masonry',        :git => 'https://github.com/iosdev-republicofapps/Masonry'
pod 'HockeySDK-Mac',  '~> 3.2.0'
pod 'MASPreferences', '~> 1.1.2'

pod 'KFAboutWindow', :git => 'https://github.com/ricobeck/KFAboutWindow.git', :tag => '0.1.1'

target 'redacted' do
end

target 'redacted tests' do
        pod 'Specta', '~> 1.0.3'
        pod 'Expecta', '~> 1.0.2'
        pod 'OCMock',  '~> 3.2.0'
end
```
Note that the permissions issue with HockeySDK-Mac happens even if HockeySDK-Mac is the only CocoaPod in the Podfile, with no other 3rd part dependencies, binaries, pods or other, so the issue is definitely with HockeySDK-Mac's CocoaPod.

Thanks again and have a nice day!

**Comment by anlinde** [comment] 2015-12-21 14:44
Can you please provide a sample project that reproduces this issue since we can't reproduce this.

**Comment by iosdev-republicofapps** [comment] 2015-12-21 14:47
I am about to fly so I can't do this now.  However, just create a basic Xcode OS X document based app project and add HockeySDK-Mac to the Podfile.  Then the permissions problem happens every time, 100% reproducible for me, on multiple different Macs, running both Yosemite and El Capitan, running different versions of Xcode also.

I can help more next week but I am out of the country on vacation this week.  :-)  I wouldn't say it's urgent to fix this this week, I just didn't think it should be closed as it wasn't resolved.  Have a Happy Holiday season!

Best,

Joel

**Comment by lumaxis** [comment] 2016-02-25 00:01
Hey @iosdev-republicofapps! Is this still an issue for you or are you fine if we close this?

**Comment by gregucsd** [comment] 2016-02-25 00:02
Haven't seen this in a while.  Close.

**Comment by lumaxis** [comment] 2016-02-25 00:03
Thanks for confirming :+1:

**Closed by lumaxis** 2016-02-25 00:03 UTC
